CREATE TABLE MARCA (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME_MARCA VARCHAR(30)
);

CREATE TABLE MODELO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	MARCA_ID INTEGER REFERENCES MARCA (ID),
	NOME VARCHAR(30),
	VALOR_FIPE NUMERIC(20,2)
);

CREATE TABLE CARRO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TIMESTAMP_CADASTRO TIMESTAMP,
	MODELO_ID INTEGER REFERENCES MODELO (ID),
	ANO INTEGER,
	COMBUSTIVEL VARCHAR(20),
	NUM_PORTAS INTEGER,
	COR VARCHAR(30)
);